import type { NextPage } from 'next'
import Head from 'next/head'
import {TextField} from "@mui/material";
import {ChangeEvent, useState} from "react";

const calculateFixedPixelCount: (nums: number[]) => number = nums => {
  if (nums.length === 0) return 0
  const filledCount = nums.reduce((previousValue, currentValue) => previousValue + currentValue, 0);
  const gutterCount = nums.length - 1
  return filledCount + gutterCount;
}

const Home: NextPage = () => {
  const [result, setResult] = useState("")
  const [error, setError] = useState(false)

  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value
    if (value == null || !/^[0-9\s]+$/.test(value)) {
      setResult("")
      setError(true)
      return
    }
    const list = value
        .trim()
        .split(" ")
        .filter(e => e.length > 0)
        .map(e => Number.parseInt(e));
    setResult(calculateFixedPixelCount(list) + "")
    setError(false)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>ピクセル計算機</h1>

        <p>
          イラストロジックのピクセル数を計算します。
        </p>

        <TextField label="塗りつぶすピクセルの数" onChange={handleInput} error={error} helperText="スペース区切りの数列を入力してください。"></TextField>
        <p>ピクセル数:{result}</p>
      </main>
    </div>
  )
}

export default Home
