name: Deploy Nuxt.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        id: configure-pages

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            packages/core/dist
          key: ${{ runner.os }}-core-build-${{ hashFiles('packages/core/dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            packages/app/dist
            packages/app/.nuxt
          key: ${{ runner.os }}-app-build-${{ hashFiles('packages/app/dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: "[core] type check"
        run: pnpm type-check:core

      - name: "[core] test"
        run: pnpm test:core

      - name: "[core] build"
        run: pnpm build:core

      - name: "[app] type check"
        run: pnpm type-check:app

      - name: "[app] test"
        run: pnpm test:app

      - name: "[app] build"
        run: pnpm build:app
        env:
          NUXT_APP_BASE_URL: ${{ steps.configure-pages.outputs.base_path }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/app/dist

  # Deployment job
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
